Use "drop_first" keyword to drop first category in categorical column
Quantco/glum pull request #571
Opened 2022-09-21 13:44 UTC by NicholasHoernleQC

**Summary**
Uses [implementation in tabmat](https://github.com/Quantco/tabmat/pull/168) to create a new default behaviour of the `GeneralizedLinearRegressorBase` to always drop the first category in a categorical column.

The purpose of this PR is to prevent singular feature matrices when there are categorical variables present. This permits to run unregularised models and improves lasso performance with categorical variables.

There were a number of tests that needed adjusting, this is because the number of categories in the tests changed. We mostly set the `drop_first=False` argument in these cases. For the `tests/glm/test_glm.py::test_categorical_types` we, rather passed the `drop_first=True` to `pd.get_dummies` to create a baseline. 

In the case that a categorical column contains only one category, and (as is default) `drop_first=True` is set, we raise a `ValueError`. 

Joint author with @MatthiasLoefflerQC :)

**Closes** #496 

**Checklist**
* [x] Added a `CHANGELOG.rst` entry

2022-09-21 16:23 UTC, MarcAntoineSchmidtQC requested changes
Great work! See my comments below.

2022-09-21 16:23 UTC, MarcAntoineSchmidtQC commented on src/glum/_glm.py
> +        f"{column_name}__{category}" for category in categories[1 * drop_first :]
```suggestion
        f"{column_name}__{category}" for category in categories[int(drop_first):]
```

explicit

2022-09-21 16:23 UTC, MarcAntoineSchmidtQC commented on src/glum/_glm.py
> +            + "This should dropped from the feature matrix."
```suggestion
            + "This should be dropped from the feature matrix."
```

2022-09-21 16:23 UTC, MarcAntoineSchmidtQC commented on src/glum/_glm.py
> +            drop_first=True,
```suggestion
            drop_first=self.drop_first,
```

Can you otherwise explain why drop_first should be enforced here?

2022-09-21 16:23 UTC, MarcAntoineSchmidtQC commented on src/glum/_glm.py
> +        drop_first: bool = True,
Same comment as above.

2022-09-21 16:23 UTC, MarcAntoineSchmidtQC commented on src/glum/_glm_cv.py
> +        drop_first: bool = True,
Same comment as above.

2022-09-21 16:25 UTC, MarcAntoineSchmidtQC commented
>  and improves lasso performance with categorical variables.

Have you documented the performance improvement with lasso? I would be curious to see the numbers.

2022-09-22 10:31 UTC, MatthiasLoefflerQC commented on src/glum/_glm.py
> +        drop_first: bool = True,
Hi Marc,

that is a good point and worthwhile discussing as there are pro's and con's to both
possibilities.

When using a penalized estimator and ``drop_first=False`` all categories in a categorical column are penalized equally. This is intuitive and makes sense to us. By contrast, if the first category is dropped, the first category is only implicitly defined through the other categories (and the intercept) and hence not penalized at the same level as the other categories.

On the other hand, when fitting the lasso, both the theoretical performance, as well as the numerical optimization performance, depend on the condition number of the feature matrix. When fitting an intercept (which is True by default) and having drop_first=False, the feature matrix is singular and the condition number unbounded. This, from a theory perspective, suggests to use ``drop_first = True`` as default when fitting the lasso.

However, Nick and I ran a lot of experiments this morning to try to validate this. For example, we ran tests with categorials in the feature matrix that were both correlated and uncorrelated with the dependent variable. Unexpectedly the results were very similar for both cases of drop_first = True/False. Importantly, the optimization did not appear to be unstable.

Hence, we agree with you to keep ``drop_first = False`` as default, as the only usecase of ``drop_first = True `` seems to be ``alpha=0``and ``solver = 'auto' `` and changed things accordingly.

2022-09-22 11:28 UTC, NicholasHoernleQC commented
> Have you documented the performance improvement with lasso

We removed this claim. After some experimentation this morning, we couldn't turn the theory into results.

2022-11-06 01:27 UTC, MarcAntoineSchmidtQC approved these changes
Sorry for the delayed review. This looks very good! Thanks a lot for the contribution.

2022-11-25 16:59 UTC, merged