Formula- and term-based Wald-tests
Quantco/glum pull request #689
Opened 2023-08-24 15:41 UTC by MartinStancsicsQC

Checklist
* [x] Added a `CHANGELOG.rst` entry

This PR uses the new functionality in glum v3 (namely the formula interface and the existence of term names) to extend the interface for the `wald_test` method. The latter now also accepts a `term` or a `formula` parameter.

2023-08-24 16:14 UTC, MatthiasSchmidtblaicherQC requested changes

2023-08-24 16:14 UTC, MatthiasSchmidtblaicherQC commented on src/glum/_glm.py
> +            Otherwise, a term is one column in the input data. In the case of
See above.

2023-08-24 16:14 UTC, MatthiasSchmidtblaicherQC commented on src/glum/_glm.py
> +            Otherwise, a term is one column in the input data. In the case of
It is probably worth expanding in docstring of `wald_test` how categoricals that are never encoded as dummies are handled. This seems like a distinguishing feature of glum's wald tests.

2023-08-24 16:16 UTC, MartinStancsicsQC commented on src/glum/_glm.py
> +            categorical variables, it translates to possibly multiple features.
Yes, exactly. I'll try to make it clearer.

2023-08-24 16:30 UTC, MartinStancsicsQC commented on src/glum/_glm.py
> +            categorical variables, it translates to possibly multiple features.
How about [this](https://github.com/Quantco/glum/blob/89a5ba4ae7f9b7861288f59670b41c551c3f9cb5/src/glum/_glm.py#L1532-L1538)?

2023-08-24 18:21 UTC, MarcAntoineSchmidtQC approved these changes
Looks good and well tested. Happy to merge this when you are ready.

2023-08-25 07:08 UTC, MatthiasSchmidtblaicherQC commented on src/glum/_glm.py
> +            categorical variables, it translates to possibly multiple features.
Looks good!

2023-08-25 07:08 UTC, MatthiasSchmidtblaicherQC approved these changes

2023-08-25 07:27 UTC, MartinStancsicsQC commented
Great, I'll merge it right after the formula PR is merged.

2023-08-28 06:16 UTC, merged