Update mirror for nightlies
Quantco/glum pull request #718
Opened 2023-10-25 21:26 UTC by jtilly

[scientific-python-nightly-wheels](https://pypi.anaconda.org/scientific-python-nightly-wheels/simple/) is a lot more up to date than [scipy-wheels-nightly](https://pypi.anaconda.org/scipy-wheels-nightly/simple/scikit-learn/).

2023-10-25 21:41 UTC, lbittarello approved these changes

2023-10-26 15:22 UTC, MarcAntoineSchmidtQC commented
With the last commit we are now able to build the environment. The tests are failing because the new channel points to numpy 2.0. From what I can see, there's a simple fix (switch from `np.Inf` to `np.inf`), and there's one that I'm not sure yet (one about [NEP50](https://numpy.org/neps/nep-0050-scalar-promotion.html))

2023-10-26 18:21 UTC, MarcAntoineSchmidtQC requested changes

2023-10-26 18:21 UTC, MarcAntoineSchmidtQC commented on .github/workflows/daily.yml
> +          PRE_WHEELS="https://pypi.anaconda.org/scientific-python-nightly-wheels/simple/"
Adding a review comment so that we do not merge this right now. We need to fix the errors caused by the newer versions.

2023-10-27 13:33 UTC, MarcAntoineSchmidtQC commented
Reading a bit on numpy 2.0. I'm worried that the switch to [scientific-python-nightly-wheels](https://pypi.anaconda.org/scientific-python-nightly-wheels/simple/) will be problematic. The fact that it's more up to date also has a downside: the probability that those packages are not yet working together is much higher.

Currently, Pandas does not work with numpy 2.0: https://github.com/pandas-dev/pandas/issues/55519.

2023-10-27 13:40 UTC, jtilly commented
Yep, got it. But that just means we shouldn't test against NumPy 2.0. I think it doesn't justify using an outdated mirror that won't get updated any longer 😉

2023-10-31 03:37 UTC, MarcAntoineSchmidtQC approved these changes

2023-10-31 03:37 UTC, merged