Fix: Incorrect use of partial in `TweedieDistribution._rowwise_gradient_hessian`
Quantco/glum pull request #889
Opened 2024-12-23 14:38 UTC by bili2002

This PR addresses issue #888 by fixing the incorrect use of partial in the `TweedieDistribution._rowwise_gradient_hessian` function.

Checklist
* [x] Added a `CHANGELOG.rst` entry

2024-12-23 16:03 UTC, stanmart requested changes
Thank you for finding fixing this! I believe there is a similar mistake here: https://github.com/Quantco/glum/blob/9c0a22185f4ad7583302e107a6a4867ac6410334/src/glum/_distribution.py#L706
Could you please address it too so that they are in the same PR?

Also, I think it'd be worth adding a test case that would have spotted these bugs (maybe [here](https://github.com/Quantco/glum/blob/9c0a22185f4ad7583302e107a6a4867ac6410334/tests/glm/test_distribution.py#L167-L176)?), but I'm also o kay with doing it later.

2024-12-23 21:11 UTC, stanmart commented
Hm, it might be a bit more involved than that. Is it possible that `inv_gaussian_log_rowwise_gradient_hessian` is incorrect? Shouldn't it be

```diff
@@ -276,12 +276,12 @@ def inv_gaussian_log_rowwise_gradient_hessian(
         inv_mu = 1 / mu[i]
         inv_mu2 = inv_mu ** 2
 
-        gradient_rows_out[i] = 2 * weights[i] * (inv_mu - y[i] * inv_mu2)
-        hessian_rows_out[i] = 2 * weights[i] * (inv_mu - 2 * y[i] * inv_mu2)
+        gradient_rows_out[i] = weights[i] * (y[i] * inv_mu2 - inv_mu)
+        hessian_rows_out[i] = weights[i] * (2 * y[i] * inv_mu2 - inv_mu)
```
instead?

2024-12-24 10:34 UTC, stanmart approved these changes
Thank you :)

2025-01-08 15:02 UTC, stanmart commented
@bili2002, do you mind if I push the fix for those formulas to this branch before merging this PR?

2025-01-09 09:03 UTC, bili2002 commented
@stanmart Sure, go ahead with the formulas!

2025-01-09 09:22 UTC, stanmart commented
@lbittarello, could you please check if my changes make sense?

2025-01-09 09:24 UTC, stanmart commented
Also, if it's correct, I  believe the [relevant part](https://github.com/Quantco/objectives/blob/06823e369680a635f10e6689b57d4db547015632/src/functions/inverse_gaussian.rs#L34-L41) of quantco/objectives needs to be updated, too.

2025-01-09 10:11 UTC, lbittarello commented on CHANGELOG.rst
> +- Fixed :class:`glum.InverseGaussianDistribution` not using the optimized gradient, hessian and deviance implementations, as well as those gradients and hessians being incorrect.
```suggestion
- Fixed a bug where :meth:`~glum.TweedieDistribution._rowwise_gradient_hessian` and :meth:`~glum.TweedieDistribution._eta_mu_deviance` would call functions with wrong arguments in the ``p = 3`` case.
- Fixed :class:`glum.InverseGaussianDistribution` not using the optimized gradient, Hessian and deviance implementations, as well as those derivatives having the wrong sign.
```

2025-01-09 10:11 UTC, lbittarello commented on src/glum/_functions.pyx
> +        hessian_rows_out[i] = weights[i] * inv_mu
```suggestion
        hessian_rows_out[i] = weights[i] * (2 * y[i] * inv_mu2 - inv_mu)
```

2025-01-09 10:18 UTC, stanmart commented on src/glum/_functions.pyx
> +        hessian_rows_out[i] = weights[i] * inv_mu
I thought this only works for tweedies with 1 ≤ p ≤ 2, because otherwise the hessian is not positive definite ([see reference](https://github.com/Quantco/glum/blob/27b123d08f5aee157b0bc1cf3357a82cba3cc512/src/glum/_functions.pyx#L359-L361))

2025-01-09 10:32 UTC, stanmart commented on src/glum/_functions.pyx
> +        hessian_rows_out[i] = weights[i] * inv_mu
Added a comment. I believe [this test case](https://github.com/Quantco/glum/blob/6f18433990bebae63af8b706ded803861819215d/tests/glm/test_distribution.py#L230) should cover the Hessian, or did you mean some other kind of test?

2025-01-09 11:16 UTC, lbittarello commented on src/glum/_functions.pyx
> +        hessian_rows_out[i] = weights[i] * inv_mu
I was rather thinking of a test of a fitted model against some benchmark (e.g., `glmnet`).

2025-01-09 11:56 UTC, stanmart commented on src/glum/_functions.pyx
> +        hessian_rows_out[i] = weights[i] * inv_mu
Ah, right, I can add a test case for that.

2025-01-09 12:10 UTC, stanmart commented on src/glum/_functions.pyx
> +        hessian_rows_out[i] = weights[i] * inv_mu
Something like [this](https://github.com/Quantco/glum/blob/b67feb429892d81c3048a09bc9257fcea2de3894/tests/glm/test_glm.py#L1273-L1344)?

2025-01-09 13:03 UTC, lbittarello approved these changes

2025-01-09 13:03 UTC, lbittarello commented on tests/glm/test_glm.py
> +    assert_allclose(glm.coef_, glmnet_coef, rtol=1e-3)
Out of curiosity, what happens if you use the full Hessian? Do the tests pass? Are the coefficients closer to `glmnet`'s?

2025-01-09 13:16 UTC, stanmart commented on tests/glm/test_glm.py
> +    assert_allclose(glm.coef_, glmnet_coef, rtol=1e-3)
The glmnet test passes and the coefficients are roughly as close as in the other case. Another test (`tests/glm/test_glm.py::test_glm_family_argument[inverse.gaussian-fam4]`) fails with a singular matrix `LinalgError`, though.

2025-01-09 13:24 UTC, stanmart commented on tests/glm/test_glm.py
> +    assert_allclose(glm.coef_, glmnet_coef, rtol=1e-3)
The failing test might not be an issue though as I believe the model was originally meant to be penalized, which but it is not since glum v3. 🤔 Anyways, I think it needs a bit more thinking and testing if we want to go with the true Hessian. I'd vote for merging this fix relatively soon, and possibly switching to the true Hessian later on if we convince ourselves that it works.

2025-01-09 13:59 UTC, merged